import {
  FaBottleWater,
  FaBoxOpen,
  FaBoxesStacked,
  FaChair,
  FaTable,
  FaHouse,
  FaPuzzlePiece,
  FaBriefcaseMedical,
  FaBox,
  FaOilCan,
  FaLayerGroup,
  FaCubes,
  FaTruck,
  FaWarehouse,
} from "react-icons/fa6";

import {
  MdDeleteOutline,
  MdOutlineSettingsSuggest,
} from "react-icons/md";

const categories = [
  {
    id: 1,
    title: "Bottles",
    products: "120+ Products",
    icon: FaBottleWater,
    color: "text-[#0B4EA2]",
  },
  {
    id: 2,
    title: "Buckets",
    products: "250+ Products",
    icon: FaBox,
    color: "text-[#84C225]",
  },
  {
    id: 3,
    title: "Containers",
    products: "180+ Products",
    icon: FaBoxOpen,
    color: "text-[#0B4EA2]",
  },
  {
    id: 4,
    title: "Dustbins",
    products: "90+ Products",
    icon: MdDeleteOutline,
    color: "text-[#84C225]",
  },
  {
    id: 5,
    title: "Drums",
    products: "150+ Products",
    icon: FaOilCan,
    color: "text-[#0B4EA2]",
  },
  {
    id: 6,
    title: "Crates",
    products: "120+ Products",
    icon: FaBoxesStacked,
    color: "text-[#0B4EA2]",
  },
  {
    id: 7,
    title: "Chairs",
    products: "80+ Products",
    icon: FaChair,
    color: "text-[#84C225]",
  },
  {
    id: 8,
    title: "Tables",
    products: "60+ Products",
    icon: FaTable,
    color: "text-[#84C225]",
  },
  {
    id: 9,
    title: "Water Tanks",
    products: "50+ Products",
    icon: FaWarehouse,
    color: "text-[#0B4EA2]",
  },
  {
    id: 10,
    title: "PVC Pipes",
    products: "70+ Products",
    icon: FaCubes,
    color: "text-[#0B4EA2]",
  },
  {
    id: 11,
    title: "Plastic Sheets",
    products: "40+ Products",
    icon: FaLayerGroup,
    color: "text-[#0B4EA2]",
  },
  {
    id: 12,
    title: "Storage Boxes",
    products: "110+ Products",
    icon: FaBox,
    color: "text-[#0B4EA2]",
  },
  {
    id: 13,
    title: "Kitchenware",
    products: "130+ Products",
    icon: FaBoxOpen,
    color: "text-[#84C225]",
  },
  {
    id: 14,
    title: "Household",
    products: "200+ Products",
    icon: FaHouse,
    color: "text-[#0B4EA2]",
  },
  {
    id: 15,
    title: "Custom Products",
    products: "100+ Products",
    icon: MdOutlineSettingsSuggest,
    color: "text-[#0B4EA2]",
  },
  {
    id: 16,
    title: "Toys",
    products: "60+ Products",
    icon: FaPuzzlePiece,
    color: "text-[#84C225]",
  },
  {
    id: 17,
    title: "Agriculture",
    products: "150+ Products",
    icon: FaTruck,
    color: "text-[#84C225]",
  },
  {
    id: 18,
    title: "Medical",
    products: "80+ Products",
    icon: FaBriefcaseMedical,
    color: "text-[#84C225]",
  },
  {
    id: 19,
    title: "Packaging",
    products: "200+ Products",
    icon: FaBoxesStacked,
    color: "text-[#84C225]",
  },
  {
    id: 20,
    title: "More Categories",
    icon: FaCubes,
    color: "text-[#0B4EA2]",
  },
];

export default categories;